version 3.4

services:
    nginx:
        image: loligatorcrwnclothingdotnet_nginx
        depends-on:
            crwn-clothing
        ports:
            - 80:80
            - 443:443
        networks:
            - nginx-proxy

    
    crwn-clothing:
        image: loligatorcrwnclothingdotnet_crwn-clothing
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:5001
            - DOTNET_USE_POLLING_FILE_WATCHER=true
        expose:
            - "5001"
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        driver: bridge
