version: '3.4'

services:
    nginx:
        image: nginx:latest-alpine
        container_name: production_nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
            
    crwn-clothing:
        build: 
            context: .
            dockerfile: ./Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:80
            - USER_SECRETS_ID=${USER_SECRETS_ID}
        exppose:
            - "80"
