version: '3.4'

services:
    nginx:
        image: nginx
        container_name: production_nginx
        depends_on:
            - crwn-clothing
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            #- /etc/letsencrypt:/etc/letsencrypt
        ports:
            - 80:80
            - 443:443
        networks:
            - nginx-proxy

    crwn-clothing:
        build: 
            context: .
            dockerfile: ./Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:5001
            - DOTNET_USE_POLLING_FILE_WATCHER=true
        expose:
            - "5001"
        ports:
            - 5001:5001
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        driver: bridge
