version: '3.4'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: production_nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            #- /etc/letsencrypt:/etc/letsencrypt
        ports:
            - 80:80
            - 443:443

    crwn-clothing:
        build: 
            context: .
            dockerfile: ./Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:5001
        ports:
            - 5001:5001
